<p>Hi!</p>

<div class="footer-actions">
    <div class="block actions">
	    <h3 class="block-title">Join us on:</h3>
		<ul id="menu-social-profiles" class="nav nav-pills text-center m-auto">
			<li class=" menu-facebook menu-item menu-facebook">
				<a target="_blank" href="https://www.facebook.com/AbCutsBrand"><span class="link-text">Facebook</span></a>
			</li>
			<li class=" menu-twitter menu-item menu-twitter">
				<a target="_blank" href="https://twitter.com/Ab_Cuts"><span class="link-text">Twitter</span></a>
			</li>
			<li class=" menu-instagram menu-item menu-instagram">
				<a target="_blank" href="https://instagram.com/abcuts/"><span class="link-text">Instagram</span></a>
			</li>
			<li class=" menu-pinterest menu-item menu-pinterest">
				<a target="_blank" href="https://www.pinterest.com/abcuts/"><span class="link-text">Pinterest</span></a>
			</li>
		</ul>
    </div>
    <div class="block actions">
	    <h3 class="block-title">Read our blog:</h3>
	    <a class="inline caps" target="_blank" href="http://blog.ricksmotorsportelectrics.com/">Ricksmotorsportelectrics.com/tips</a>
    </div>
</div>