<section class="blocks col-2 adjust-wrap support">
	<div class="block free_shipping">
		<div class="wrap">
		<?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('free_shipping')->toHtml(); ?>
		</div>
	</div>
	<div class="block help">
		<div class="wrap">
		<?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('help')->toHtml(); ?>
		</div>
	</div>
</section>