<section class="adjust-fw skew-item youtube">
	<div class="blocks col-2 youtube adjust-wrap">
		<div class="video-ratio">
			<div class="content">
				<?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('youtube_embed')->toHtml(); ?>
			</div>
		</div>
		<aside class="block youtube-copy">
			<?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('youtube')->toHtml(); ?>
		</aside>
	</div>
</section>