<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<p>Testing 1 2 3</p>
<?php /* @escapeNotVerified */ echo $pageData->getPageContent(); ?>
jsnfianofmapso

<?php echo $pageData->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('free_shipping')->toHtml(); // Change block_identifier with Your Static Block Identifire ?>