<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php /* @escapeNotVerified */ echo $pageData->getPageContent(); ?>

<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('free_shipping')->toHtml();?>

<?php echo $pageData->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('free_shipping')->toHtml(); // Change block_identifier with Your Static Block Identifire ?>